
PROJECT_HEADER_FILES=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.HEADER.FILES
PROJECT_LIBRARY_DIRECTORY=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.LIBRARY
BASE_DIRECTORY=~/PCYNLITX_TLV_ENCODER_TEST
APP_SPEC_LIBRARY_HEADERS=$BASE_DIRECTORY/Thread_Server_Include_Directory
TEST_DIRECTORY=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_PCYNLITX/Test.Binaries

g++ -std=c++14 -o pcynlitx_tlv_encoder_test  -I$PROJECT_HEADER_FILES \
    -L$PROJECT_LIBRARY_DIRECTORY pcynlitx_tlv_encoder_test.cpp -include Cpp_FileOperations.h -lmptools

mv pcynlitx_tlv_encoder_test $TEST_DIRECTORY
