
PROJECT_HEADERS=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.HEADER.FILES
PROJECT_LIBRARY=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.LIBRARY
BASE_DIR=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_C++_STD_THREAD
TEST_DIR=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_C++_STD_THREAD/Test.Binaries
TEST_PROGRAMS=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_C++_STD_THREAD/Sub.Class.TestPrograms

g++ -o data_extracter_test -I$PROJECT_HEADERS -I$BASE_DIR -L$PROJECT_LIBRARY \
  $TEST_PROGRAMS/data_extracter_test.cpp \
  $BASE_DIR/data_extracter.cpp -include data_extracter.h -include StringOperator.h \
  -include CharOperator.h -include Cpp_FileOperations.h -lmptools

mv data_extracter_test $TEST_DIR
