
PROJECT_HEADERS=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.HEADER.FILES
PROJECT_LIBRARY=~/PCYNLITX.PROJECT.LIBRARY/PROJECT.LIBRARY
BASE_DIR=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_C++_STD_THREAD
TEST_DIR=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_C++_STD_THREAD/Test.Binaries
TEST_PROGRAMS=~/PCYNLITX.PROJECT/PROJECT.TEST.TOOLS/TLV_ENCODER_C++_STD_THREAD/Sub.Class.TestPrograms

g++ -o string_reader_test -I$PROJECT_HEADERS -I$BASE_DIR -L$PROJECT_LIBRARY \
  $TEST_PROGRAMS/string_reader_test.cpp $BASE_DIR/string_reader.cpp \
   -include string_reader.h -include Cpp_FileOperations.h -lpthread -lmptools

mv string_reader_test $TEST_DIR
