
#ifndef EVENT_TABLE_HEADER_SNAP_H
#define EVENT_TABLE_HEADER_SNAP_H

#include "MainFrame_Snap.h"

BEGIN_EVENT_TABLE(MainFrame_Snap,wxFrame)
  EVT_MENU(wxID_OPEN,MainFrame_Snap::OnOpen)
  EVT_MENU(wxID_EXIT,MainFrame_Snap::OnQuit)
  EVT_MENU(ID_RUN_LIBRARY_BUILDER,MainFrame_Snap::RunLibraryBuilder)
  EVT_MENU(ID_RUN_EXECUTABLE_BINARY_BUILDER,MainFrame_Snap::RunExeBuilder)
  EVT_MENU(ID_SELECT_PROJECT_FILE,MainFrame_Snap::SelectProjectFile)
  EVT_MENU(ID_FILE_SAVE,MainFrame_Snap::File_Save)
  EVT_MENU(ID_SELECT_PROJECT_FOLDER,MainFrame_Snap::DirectoryOpen)
  EVT_MENU(ID_OPEN_EMPTY_PROJECT_FILE,MainFrame_Snap::OpenEmptyProjectFile)
  EVT_MENU(ID_SHOW_PROJECT_FILE,MainFrame_Snap::ShowProjectFile)
  EVT_MENU(ID_OPEN_INTROPAGE,MainFrame_Snap::OpenIntroPage)
  EVT_MENU(ID_OPEN_TREE_WIEW,MainFrame_Snap::Re_Open_Project_Directory)
  EVT_MENU(ID_SHOW_AUTOR_INFO,MainFrame_Snap::ShowAuthor)
  EVT_MENU(ID_SHOW_PROJECT_DESCRIPTOR_FILE_LOCATION,MainFrame_Snap::ShowProjectFileLocation)
  EVT_MENU(ID_SHOW_PROJECT_DIRECTORY_LOCATION,MainFrame_Snap::ShowProjectDirectoryLocation)
  EVT_MENU(ID_INCREASE_FONT_SIZE,MainFrame_Snap::Increase_Font_Size)
  EVT_MENU(ID_DECREASE_FONT_SIZE,MainFrame_Snap::Decrease_Font_Size)
  EVT_MENU(ID_UNDO_CHANGES,MainFrame_Snap::Undo_Changes)
  EVT_MENU(ID_REDO_CHANGES,MainFrame_Snap::Redo_Changes)
  EVT_MENU(ID_INPUT_HEADER_FILE_LOCATION,MainFrame_Snap::Enter_Header_File_Location)
  EVT_MENU(ID_INPUT_SOURCE_FILE_LOCATION,MainFrame_Snap::Enter_Source_File_Location)
  EVT_MENU(ID_INPUT_LIBRARY_LOCATION,MainFrame_Snap::Enter_Library_Location)
  EVT_MENU(ID_INPUT_HEADER_FILE,MainFrame_Snap::Enter_Header_File)
  EVT_MENU(ID_INPUT_SOURCE_FILE_NAME,MainFrame_Snap::Enter_Source_File)
  EVT_MENU(ID_INPUT_LIBRARY_NAME,MainFrame_Snap::Enter_Library_Name)
  EVT_MENU(ID_INPUT_CONSTRUCTION_POINT,MainFrame_Snap::Enter_Construction_Point)
  EVT_MENU(ID_INPUT_THREAD_FUNCTION_NAME,MainFrame_Snap::Enter_Thread_Function_Name)
  EVT_MENU(ID_INPUT_THREAD_NUMBER,MainFrame_Snap::Enter_Thread_Number)
  EVT_MENU(ID_INPUT_EXE_FILE_NAME,MainFrame_Snap::Enter_Exe_File_Name)
  EVT_MENU(ID_INPUT_ITC_HEADER_FILE_NAME,MainFrame_Snap::Enter_ITC_Class_Header_File_Name)
  EVT_MENU(ID_INPUT_ITD_HEADER_FILE_NAME,MainFrame_Snap::Enter_IT_Data_Type_Header_File_Name)
  EVT_MENU(ID_INPUT_ITD_DATA_NAME,MainFrame_Snap::Enter_IT_Data_Type_Name)
  EVT_MENU(ID_INPUT_NAMESPACE,MainFrame_Snap::Enter_Namespace)
  EVT_MENU(ID_CLEAR_STYLE,MainFrame_Snap::Clear_Style)
  EVT_MENU(ID_RELOAD_STYLE,MainFrame_Snap::Reload_Default_Style)
  EVT_MENU(ID_SAVE_AS,MainFrame_Snap::Save_File_As)
  EVT_MENU(ID_CLEAR_TEXT,MainFrame_Snap::Clear_Text)
  EVT_MENU(ID_SET_CURSOR_TYPE_DEFAULT,MainFrame_Snap::Load_Default_Cursor)
  EVT_MENU(ID_CHANGE_CURSOR_TYPE,MainFrame_Snap::Change_Cursor_Type)
  EVT_MENU(ID_SET_CARET_LINE_VISIBLE,MainFrame_Snap::Set_Caret_Line_Visible)
  EVT_MENU(ID_SET_CARET_LINE_INVISIBLE,MainFrame_Snap::Set_Caret_Line_InVisible)
  EVT_MENU(ID_USE_BLOCK_CARET,MainFrame_Snap::Use_Block_Caret)
  EVT_MENU(ID_USE_DEFAULT_CARET,MainFrame_Snap::Use_Default_Caret)
  EVT_MENU(ID_NEW_FILE,MainFrame_Snap::New_File)
  EVT_MENU(ID_BOLD_STYLE,MainFrame_Snap::Use_Bold_Styling)
  EVT_MENU(ID_SHOW_DESCRIPTIONS,MainFrame_Snap::Show_Descriptions)
  EVT_CLOSE(MainFrame_Snap::OnClose)
  EVT_PAINT(MainFrame_Snap::OnPaint)
  EVT_SIZE(MainFrame_Snap::OnSize)
  EVT_AUI_PANE_CLOSE(MainFrame_Snap::Close_Directory_Pane)
  EVT_END_PROCESS(wxID_ANY,MainFrame_Snap::Process_End)
  EVT_CHAR_HOOK(MainFrame_Snap::KeyboardEvent)
  EVT_TREE_ITEM_ACTIVATED(wxID_ANY,MainFrame_Snap::FileSelect)
  EVT_TREE_BEGIN_LABEL_EDIT(wxID_ANY,MainFrame_Snap::FileNameEdit)
END_EVENT_TABLE()

#endif /* EVENT_TABLE_HEADER_SNAP_H */
